version: '3.7'

services:
    frontend-service:
      container_name: frontend-service
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:80"
      labels:
        NAME: "frontend-service"
        kompose.service.type: LoadBalancer
      networks:
        - net
      depends_on:
        - rabbitmq
        - zipkin
        - authentication-service
        - user-service
        - company-management-service
        